Using java8 specific function String.join causes travis to fail with the following error while building java7 binary.
```
   testGetTasksToLaunchForOneTopologyWithOneOffer(storm.mesos.MesosNimbusTest)  Time elapsed: 0.158 sec  <<< ERROR!
   java.lang.NoSuchMethodError: java.lang.String.join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String;
```

Fixing ^^ by using org.apache.commons.lang3.StringUtils.join instead of java.lang.String.join